### ISSUE TITLE
Change references for benchmark functions

### ISSUE THREAD

**Issue by HeleNoir** [mahf-opt/mahf#133]
The website referenced currently for our benchmark functions doesn't exist any more.

`//! Collection of test functions from [benchmarkfcns.xyz](http://benchmarkfcns.xyz) without Quartic function and Xin-She Yang Nr. 1 function`

We should try to find better references, but at least remove the links.

**Comment by Saethox** [comment]
https://arxiv.org/abs/1308.4008 and https://www.sfu.ca/~ssurjano/optimization.html should contain most of the benchmark functions we have implemented, but probably not all of them.

**Comment by Saethox** [comment]
References were fixed in `mahf-bmf`, at least as long as https://mazhar-ansari-ardeh.github.io/BenchmarkFcns/ stays online.
