### ISSUE TITLE
Move mutation probabilities out of operators

### ISSUE THREAD

**Issue by HeleNoir** [mahf-opt/mahf#139]
Some mutation operators have a mutation probability `pm`  as a parameter. These should be removed from the operators, as a condition should be included in the configuration before the mutation.

Note: this only concerns the mutation probabilities `pm`, the mutation rates `rm` are fine as they are!

**Comment by Saethox** [comment]
So basically, wrap the `mutation` like this: `.if_(branching::RandomChance::new(pm), |builder| builder.do_(mutation))`? 
Either mutate the entire population or nothing?

**Comment by HeleNoir** [comment]
Yes, that's what I meant. It makes more sense, in my opinion, regarding the overall structure of MAHF and especially how you implemented CRO.
