### ISSUE TITLE
Multiple diversity measures

### ISSUE THREAD

**Issue by HeleNoir** [mahf-opt/mahf#140]
Before I invest a lot of time trying, I thought I would ask first:

Can we calculate the diversity with several measures for one run of an algorithm? And can we log all of them? @luleyleo @Saethox

**Comment by luleyleo** [comment]
Yes, we can! The easiest way to do so would be one state type per diversity metric.

**Comment by HeleNoir** [comment]
Can either of you please adapt this, I just have not enough time to think it through...

**Comment by Saethox** [comment]
I'm working on it.
