### ISSUE TITLE
`Individual::evaluate_with` does not take a mutable function.

### ISSUE THREAD

**Issue by luleyleo** [mahf-opt/mahf#177]
https://github.com/mahf-opt/mahf/blob/e7a520afd5b16d7b15ac13ddff463df791429080/src/problems/individual.rs#L79-L84

This function should take an `FnMut`. Otherwise, you can't use it to evaluate problems where the evaluation function mutates the evaluator.

**Comment by Saethox** [comment]
Resolved with #173.
