### ISSUE TITLE
Coco: Remove C dependency for legacy code

### ISSUE THREAD

**Issue by luleyleo** [mahf-opt/mahf#6]
In order to avoid reimplementing the legacy C code of Coco's bbob suite, I instead compiled it and liked it with mahf. It would be nice to keep this project entirely in Rust, so it should be (auto?) converted to Rust at some point.

It is important to keep it exactly the same in terms of behaviour, so this will be a rather annoying task.

https://github.com/luleyleo/mahf/blob/c44a55a6c71685cc970e8d2dfefc1e2f46c09417/src/problems/coco/suits/bbob/legacy_code.c#L1-L7

**Comment by HeleNoir** [comment]
Can we close this or do we still need it for any reason?

**Comment by luleyleo** [comment]
This can be closed in favor of #155
